### PR TITLE
Mobile Responsiveness Fixes

### PR DESCRIPTION
**Pull request by mjherich**
# Description

Went through every view plus header and footer and updated styles to be responsive for all sizes.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change status
- [x] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

Deployed to https://fz5dii7b6h.execute-api.us-east-1.amazonaws.com/dev-matt/. Looks good on all screen widths.

# Checklist:
Everything in this checklist is required for each PR.  Please do not approve a PR that does not have all of these items.  

- [ ] I have pulled from master before submitting this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts
- [x] Any env variables or config options that are needed have been stated in the README
- [ ] My code has been reviewed by at least one peer (the peer review to approve a PR counts.  The reviewer must download and test the code)
- [x] NO API KEYS ARE PUSHED UP

### CODE REVIEW

**Comment by nisaChampagne** [comment]
looks good to go for QA

**Comment by seanwu20** [comment]
The navbar on mobile is a little crowded. Is this unavoidable due to the words?

**Comment by mjherich** [comment]
> The navbar on mobile is a little crowded. Is this unavoidable due to the words?

I agree, I think making the links stack will be a decent solution.

**Comment by mjherich** [comment]
@seanwu20 Made the font size and margin smaller on smaller screens to clean it up.

**Pull request merged**
